---
title: "Class 6 R Functions"
author: "Zach Goldberg"
date: "10/18/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#Importing different flat files

Test1
```{r}
test1 <- read.csv("test1.txt", header = TRUE)
test1
```

Test2
```{r}
test2 <- read.table("test2.txt", header = TRUE, sep = "$")
test2
```

Test 3
```{r}
test3 <- read.table("test3.txt", sep = "", header = FALSE)
test3
```

#Writing a function

###Original code
```{r}
# Can you improve this analysis code? 
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug 
s2 <- read.pdb("1AKE") # kinase no drug 
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA") 
s2.chainA <- trim.pdb(s2, chain="A", elety="CA") 
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b 
s2.b <- s2.chainA$atom$b 
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor") 
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor") 
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")

hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) ) 
plot(hc)
```

###Snippet from original code above
```{r}
library(bio3d)

x <- read.pdb("4AKE")
x.chainA <- trim.pdb(x, chain="A", elety="CA") 
x.b <- x.chainA$atom$b 
plotb3(x.b, sse=x.chainA, typ="l", ylab="Bfactor") 
```
### Function from snippet
```{r}
bfactor.plot <- function(p){
  require(bio3d)
  x <- read.pdb(p)
  x.chainA <- trim.pdb(x, chain="A", elety="CA") 
  x.b <- x.chainA$atom$b 
  plotb3(x.b, sse=x.chainA, typ="l", ylab="Bfactor") 
}

bfactor.plot("4AKE")
```
Function that works with vectors
```{r}
apply
```

